recruiting/urls.py
""" recruiting URL Configuration """
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from recruiting import signals
from interviews import views as interviewsViews
from jobs import views as jobsViews
from publicsite import views as publicViews
from candidates import views as candidatesViews
from recruiters import views as recruitersViews
from dashboards import views as dashboardViews
from campaigns import views as campaignViews

urlpatterns = [
    url(r'^$', publicViews.home, name='home'),
    url(r'^home/$', publicViews.home, name='home'),
    url(r'^services/$', publicViews.services, name='services'),
    url(r'^portfolio/$', publicViews.portfolio, name='portfolio'),
    url(r'^about/$', publicViews.about, name='about'),
    url(r'^careers/$', publicViews.careers, name='careers'),
    url(r'^careers/(?P<job_id>\d+)/$', publicViews.career_details, name='career_details'),
    url(r'^careers/(?P<job_id>\d+)/apply/$', publicViews.career_apply, name='career_apply'),
    url(r'^careers/(?P<job_id>\d+)/(?P<candidate_id>\d+)/responseForm/$', publicViews.career_response_form, name='career_response_form'),
    url(r'^dashboards/$', dashboardViews.dashboards, name='dashboards'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^jobs/$', jobsViews.view_jobs, name='jobs'),
    url(r'^jobs/xml_feed$', jobsViews.xml_feed, name='xml_feed'),
    url(r'^jobs/(?P<job_id>\d+)/$', jobsViews.view_job_details, name='job_details'),
    url(r'^jobs/(?P<job_id>\d+)/apply/$', jobsViews.apply, name='apply'),
    url(r'^jobs/(?P<job_id>\d+)/unpublish/$', jobsViews.unpublish, name='unpublish'),
    url(r'^jobs/(?P<job_id>\d+)/publish/$', jobsViews.publish, name='publish'),
    url(r'^jobs/(?P<job_id>\d+)/pipeline/$', jobsViews.pipeline, name='pipeline'),
    url(r'^jobs/fetch/$', jobsViews.fetch, name='fetch'),
    url(r'^campaigns/mailcampaign/(?P<campaign_id>\d+)/startVendor/$', campaignViews.start_vendor_campaign, name='start_campaign'),
    url(r'^campaigns/mailcampaign/(?P<campaign_id>\d+)/startCandidate/$', campaignViews.start_candidate_campaign, name='start_campaign'),
    url(r'^candidates/$', candidatesViews.view_candidates, name='candidates'),
    url(r'^candidates/apply/$', candidatesViews.apply, name='candidate_apply'),
    url(r'^candidates/apply/success/$', candidatesViews.apply_success, name='candidate_apply_success'),
    url(r'^candidates/(?P<candidate_id>\d+)/pipeline/$', candidatesViews.pipeline, name='pipeline'),
    url(r'^recruiters/', recruitersViews.view_recruiters, name='recruiters'),
    url(r'^available/(?P<bu_id>\d+)/$', interviewsViews.available, name='available'),
    url(r'^availability/(?P<bu_id>\d+)/$', interviewsViews.availability, name='availability'),
    url(r'^interviews/', interviewsViews.interview_requests, name='interviews'),
]

candidates/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.conf import settings
from vendors.models import Vendor
from recruiting.choices import *
from jobs.models import Job, JobMandatoryQualification, JobRequestedQualification


class Candidate(models.Model):
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE, related_name='candidates', blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    first_name = models.CharField(max_length=250, blank=True)
    last_name = models.CharField(max_length=250, blank=True)
    email = models.CharField(max_length=250, blank=True)
    status = models.CharField(choices=CANDIDATE_STATUS_CHOICES, max_length=100, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    gender = models.CharField(choices=(('male', 'Male'), ('female', 'Female'),), max_length=10, blank=True, null=True)
    education = models.CharField(
        max_length=25,
        blank=True,
        choices=EDUCATION_CHOICES,
    )
    education_major = models.CharField(max_length=250, blank=True)
    work_status = models.CharField(max_length=100, blank=True)
    referral_method = models.CharField(max_length=100, blank=True)
    phone_number = models.CharField(blank=True, max_length=50)
    preferred_communication_method = models.CharField(verbose_name='Communication', max_length=100, blank=True)
    best_contact_time = models.CharField(max_length=250, blank=True)
    skillset = models.CharField(max_length=250, blank=True, null=True)
    notes = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    last_modified = models.DateTimeField(auto_now_add=False, auto_now=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    initial_contact_date = models.DateTimeField(verbose_name='Contacted', auto_now_add=False, auto_now=False, blank=True, null=True)
    response_form_sent_date = models.DateTimeField(verbose_name='Form Sent', auto_now_add=False, auto_now=False, blank=True, null=True)
    response_form_completed_date = models.DateTimeField(verbose_name='Form Completed', auto_now_add=False, auto_now=False, blank=True, null=True)

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)


class CandidateApplication(models.Model):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name='applications')
    job = models.ForeignKey(Job, related_name='applications')
    last_modified = models.DateTimeField(auto_now_add=False, auto_now=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return '%s %s Application' % (self.candidate.first_name, self.candidate.last_name)


class CandidateResponse(models.Model):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name='responses')
    job = models.ForeignKey(Job, related_name='responses')
    last_modified = models.DateTimeField(auto_now_add=False, auto_now=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return '%s %s Response Form' % (self.candidate.first_name, self.candidate.last_name)


class CandidateResponseMandatoryQualification(models.Model):
    candidateResponse = models.ForeignKey(CandidateResponse, on_delete=models.CASCADE, related_name='mandatoryQualifications')
    mandatoryQualification = models.ForeignKey(JobMandatoryQualification, on_delete=models.CASCADE, related_name='candidateResponses')
    responseText = models.TextField(null=True, blank=True)


class CandidateResponseRequestedQualification(models.Model):
    candidateResponse = models.ForeignKey(CandidateResponse, on_delete=models.CASCADE, related_name='requestedQualifications')
    requestedQualification = models.ForeignKey(JobRequestedQualification, on_delete=models.CASCADE, related_name='candidateResponses')
    responseText = models.TextField(null=True, blank=True)


class CandidateDocument(models.Model):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name='documents')
    display_name = models.CharField(blank=True, null=True, max_length=100)
    file_type = models.CharField(blank=True, null=True, max_length=100, choices=FILE_TYPE_CHOICES)
    headers = models.TextField(null=True, blank=True,)
    document = models.FileField(upload_to=settings.ATTACHMENT_UPLOAD_TO,)
    last_modified = models.DateTimeField(auto_now_add=False, auto_now=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)

dashboards/models.py
from django.db import models

# Create your models here.

candidates/forms.py
from django import forms
from django_countries.fields import LazyTypedChoiceField
from django_countries import countries
from recruiting.choices import (TIMEZONE_CHOICES, EDUCATION_CHOICES, GENDER_CHOICES)

class UserApplyStep1Form(forms.Form):
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    email = forms.EmailField(max_length=50)
    citizenship = LazyTypedChoiceField(choices=countries)
    skype_id = forms.CharField(label='Skype ID', max_length=20)
    timezone = forms.ChoiceField(choices=TIMEZONE_CHOICES)

class UserApplyStep2Form(forms.Form):
    birth_year = forms.IntegerField(min_value=1950, max_value=2000)
    gender = forms.TypedChoiceField(choices=GENDER_CHOICES)
    education = forms.TypedChoiceField(choices=EDUCATION_CHOICES)
    education_major = forms.CharField(max_length=50)
    image = forms.ImageField()
    resume = forms.FileField()

class ApplyNowForm(forms.Form):
    firstName = forms.CharField(max_length=30, required=True)
    lastName = forms.CharField(max_length=100, required=True)
    email = forms.CharField(max_length=100, required=True)
    phone = forms.CharField(max_length=20, required=True)
    preferredCommunicationMethod = forms.CharField(max_length=100, required=True)
    bestContactTime = forms.CharField(max_length=250, required=True)
    message = forms.CharField(max_length=1000, required=False)
    resume = forms.FileField(required=False)

candidates/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponseRedirect
from accounts.models import UserProfile
import xmlrpclib
import base64
from django.conf import settings
from django.contrib.auth.decorators import login_required

from .models import Candidate, CandidateDocument
from .forms import UserApplyStep1Form, UserApplyStep2Form

@login_required
def view_candidates(request):
    candidates = Candidate.objects.all()

    context = {'candidates': candidates}
    return render(request, 'candidates/candidates.html', context)

def apply(request):

	key = request.GET.get('key', None)
	user = UserProfile.verify_token(key)

	if not key and request.method == 'POST':
		
		form = UserApplyStep1Form(request.POST)

		if form.is_valid():
			data = form.data
			first_name = data['first_name']
			last_name = data['last_name']
			email = data['email']
			citizenship = data['citizenship']
			skype_id = data['skype_id']
			timezone = data['timezone']

			user, created = User.objects.get_or_create(
				first_name=first_name,
				last_name=last_name,
				email=email,
				username=email
				)

			if not created:
				messages.add_message(request, messages.ERROR,
					email + ' has already been registered.')
			else:
				userprofile = UserProfile(
					user=user,
					timezone=timezone,
					citizenship=citizenship,
					skype_id=skype_id,
					user_type='Candidate'
					)

				userprofile.save()
				
				key = user.userprofile.generate_token()
				
				return HttpResponseRedirect(
					reverse('candidate_apply') + '?key=' + key)


	elif not key and request.method == 'GET':
		form = UserApplyStep1Form()

	elif key and user and request.method == 'POST':

		form = UserApplyStep2Form(request.POST, request.FILES)
	
		if form.is_valid():
			files = form.files
			data = form.data
	
			try:
				candidate = user.candidate
				candidate.birth_year = data['birth_year']
				candidate.gender = data['gender']
				candidate.education = data['education']
				candidate.education_major = data['education_major']
				candidate.image = files['image']
				candidate.save()
			except Candidate.DoesNotExist:
				candidate = Candidate.objects.create(user=user, 
					birth_year=data['birth_year'],
					gender=data['gender'],
					education=data['education'],
					education_major=data['education_major'],
					image=files['image']
					)
			CandidateDocument.objects.create(
				candidate=candidate,
				document=files['resume'],
				document_type='Resume'
				)

			messages.add_message(request, messages.SUCCESS,
				'Form submitted successfully.')

			return HttpResponseRedirect(
					reverse('candidate_apply_success') + '?key=' + key)

	elif key and user and request.method == 'GET':
		form = UserApplyStep2Form()

	else:
		messages.add_message(request, messages.ERROR,
			'A valid application key is required to submit documents. ' +
			'Please contact the administrator.')
		form = None

	return render(request, 'candidates/apply.html', {'form': form})


def apply_success(request):
    key = request.GET.get('key', None)
    user = UserProfile.verify_token(key)

    if not key or not user:
        messages.add_message(request, messages.ERROR,
                             'A valid application key is required to view this page.')
    else:
        jobs_url = reverse('jobs') + '?key=' + key
        availability_url = reverse('available', args=[user.id]) + '?key=' + key

    return render(request, 'candidates/apply.html',
                  {'success': 'success',
                   'jobs_url': jobs_url,
                   'availability_url': availability_url
                   })

def pipeline(request, candidate_id):
    candidate = Candidate.objects.get(id=candidate_id)

    # authenticate
    common = xmlrpclib.ServerProxy('{}/xmlrpc/2/common'.format(settings.ODOO_SERVER_URL))
    uid = common.authenticate(settings.ODOO_SERVER_DATABASE, settings.ODOO_SERVER_USERNAME, settings.ODOO_SERVER_PASSWORD, {})

    models = xmlrpclib.ServerProxy('{}/xmlrpc/2/object'.format(settings.ODOO_SERVER_URL))

    for application in candidate.applications.all():
        job = application.job
        hrJobIds = models.execute_kw(settings.ODOO_SERVER_DATABASE, uid, settings.ODOO_SERVER_PASSWORD, 'hr.job', 'search',
                                     [[['name', '=', "%s" % (job.title)]]],
                                     {'limit': 1})

        if hrJobIds:
            # check to see if this candidate exists already
            count = models.execute_kw(settings.ODOO_SERVER_DATABASE, uid, settings.ODOO_SERVER_PASSWORD, 'hr.applicant', 'search_count',
                                      [[['email_from', '=', "%s" % (candidate.email)], ['job_id', '=', hrJobIds[0]]]])

            # create a new candidate
            if count == 0:
                id = models.execute_kw(settings.ODOO_SERVER_DATABASE, uid, settings.ODOO_SERVER_PASSWORD, 'hr.applicant', 'create', [{
                    'partner_name': "%s %s" % (candidate.first_name, candidate.last_name),
                    'display_name': "%s %s" % (candidate.first_name, candidate.last_name),
                    'name': "%s %s" % (candidate.first_name, candidate.last_name),
                    'email_from': '%s' % candidate.email,
                    'partner_phone': '%s' % candidate.phone_number,
                    'job_id': hrJobIds[0]
                }])

                for attachment in candidate.documents.all():
                    file = attachment.document.file
                    file.open(mode='rb')
                    lines = file.read()
                    file.close()

                    id = models.execute_kw(settings.ODOO_SERVER_DATABASE, uid, settings.ODOO_SERVER_PASSWORD, 'ir.attachment', 'create', [{
                        'res_model': 'hr.applicant',
                        'res_id': id,
                        'name': "%s" % attachment.display_name,
                        'display_name': "%s" % attachment.display_name,
                        'datas_fname': "%s" % attachment.display_name,
                        'store_fname': "%s" % attachment.display_name,
                        'type': 'binary',
                        'datas': base64.b64encode(lines)
                    }])

    messages.add_message(request, messages.SUCCESS, 'Candidate pipeline started successfully.')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

dashboards/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from datetime import date, datetime
from candidates.models import Candidate
from jobs.models import Job

from interviews.models import InterviewInvitation, InterviewRequest
from jobs.models import Job

@login_required
def dashboards(request):
    if request.user.is_authenticated:

        user_type = request.user.userprofile.user_type

        if user_type == 'Candidate':
            return render(request, 'candidates/dashboard.html')

        if user_type == 'Recruiter':
            initial_contacts_sent = Candidate.objects.filter(initial_contact_date__isnull=True).count()
            response_forms_sent = Candidate.objects.filter(response_form_sent_date__isnull=False).count()
            response_forms_completed = Candidate.objects.filter(response_form_completed_date__isnull=False).count()
            open_jobs = Job.objects.filter(is_active__exact=True).filter(is_featured__exact=True).filter(submission_date__gte=date.today()).count()

            context = {
                'initial_contacts_sent': initial_contacts_sent,
                'response_forms_sent': response_forms_sent,
                'response_forms_completed': response_forms_completed,
                'open_jobs': open_jobs,
            }

            return render(request, 'recruiters/dashboard.html', context)

        if user_type == 'Employer':
            return render(request, 'employers/dashboard.html')

    return render(request, 'dashbaords/home.html')

candidates/templates/candidates/_progress.html
<div class="row bs-wizard" style="border-bottom:0;">
    
    <div id="step1" class="col-xs-3 bs-wizard-step">
      <div class="text-center bs-wizard-stepnum">Step 1</div>
      <div class="progress"><div class="progress-bar"></div></div>
      <a href="#" class="bs-wizard-dot"></a>
      <div class="bs-wizard-info text-center">Basic Information</div>
    </div>
    
    <div id="step2" class="col-xs-3 bs-wizard-step"><!-- complete -->
      <div class="text-center bs-wizard-stepnum">Step 2</div>
      <div class="progress"><div class="progress-bar"></div></div>
      <a href="#" class="bs-wizard-dot"></a>
      <div class="bs-wizard-info text-center">Resume</div>
    </div>
    
    <div id="step3" class="col-xs-3 bs-wizard-step"><!-- complete -->
      <div class="text-center bs-wizard-stepnum">Step 3</div>
      <div class="progress"><div class="progress-bar"></div></div>
      <a href="#" class="bs-wizard-dot"></a>
      <div class="bs-wizard-info text-center">Submit!</div>
    </div>
</div>

candidates/templates/candidates/_progress_style.html
<style>
.bs-wizard {margin-top: 40px;}

/*Form Wizard*/
.bs-wizard {border-bottom: solid 1px #e0e0e0; padding: 0 0 10px 0;}
.bs-wizard > .bs-wizard-step {padding: 0; position: relative;}
.bs-wizard > .bs-wizard-step + .bs-wizard-step {}
.bs-wizard > .bs-wizard-step .bs-wizard-stepnum {color: #595959; font-size: 16px; margin-bottom: 5px;}
.bs-wizard > .bs-wizard-step .bs-wizard-info {color: #999; font-size: 14px;}
.bs-wizard > .bs-wizard-step > .bs-wizard-dot {position: absolute; width: 30px; height: 30px; display: block; background: #fbe8aa; top: 45px; left: 50%; margin-top: -15px; margin-left: -15px; border-radius: 50%;} 
.bs-wizard > .bs-wizard-step > .bs-wizard-dot:after {content: ' '; width: 14px; height: 14px; background: #fbbd19; border-radius: 50px; position: absolute; top: 8px; left: 8px; } 
.bs-wizard > .bs-wizard-step > .progress {position: relative; border-radius: 0px; height: 8px; box-shadow: none; margin: 20px 0;}
.bs-wizard > .bs-wizard-step > .progress > .progress-bar {width:0px; box-shadow: none; background: #fbe8aa;}
.bs-wizard > .bs-wizard-step.complete > .progress > .progress-bar {width:100%;}
.bs-wizard > .bs-wizard-step.active > .progress > .progress-bar {width:50%;}
.bs-wizard > .bs-wizard-step:first-child.active > .progress > .progress-bar {width:0%;}
.bs-wizard > .bs-wizard-step:last-child.active > .progress > .progress-bar {width: 100%;}
.bs-wizard > .bs-wizard-step.disabled > .bs-wizard-dot {background-color: #f5f5f5;}
.bs-wizard > .bs-wizard-step.disabled > .bs-wizard-dot:after {opacity: 0;}
.bs-wizard > .bs-wizard-step:first-child  > .progress {left: 50%; width: 50%;}
.bs-wizard > .bs-wizard-step:last-child  > .progress {width: 50%;}
.bs-wizard > .bs-wizard-step.disabled a.bs-wizard-dot{ pointer-events: none; }
/*END Form Wizard*/	
</style>

candidates/templates/candidates/apply.html
{% extends 'base.html' %}

{% block head %}
    {{ block.super }}

    {% include 'candidates/_progress_style.html' %}

{% endblock %}

{% block content %}

    {% if form %}
        {% include 'candidates/_progress.html' %}
        <h1>Application Page</h1>
        <form method='post' enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="fieldWrapper">
                    {{ field.label_tag }} {{ field }}
                    {{ field.errors }}
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}
            <input type='submit' value='Submit'>
        </form>
    {% endif %}

    {% if success %}
        <h1>Congratulations! <small>Application Submitted</small></h1>
        <div class='row'>
            <div class='col-md-offset-3 col-md-6'>
                <h3>What next?</h3>
                <p>Your application materials have been received and our being reviewed. To speed
                    up the job search please request interviews for jobs of interest and provide your
                    interview time availability below.
                <ul>
                    <li>
                        <a href='{{ jobs_url }}'>
                            Request job interviews
                        </a>
                    </li>
                    <li>
                        <a href='{{ availability_url }}'>
                            Provide your interview availability
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    {% endif %}

{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script>
        $('#step1').addClass('complete');
    </script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.6/jstz.min.js"></script>
    <script>
        var timezoneValues = Object.values(jstz.olson.timezones);
        var detectedTimezone = jstz.determine().name();
        if(timezoneValues.indexOf(detectedTimezone) != -1) {
            $('#id_timezone').prop('selected', true).val(detectedTimezone);
        }
    </script>
{% endblock %}

candidates/templates/candidates/candidates.html
{% extends 'base.html' %}

{% block head %}
    {{ block.super }}

{% endblock %}

{% block content %}
    <div class='row'>
        <div class='col-xs-12 col-sm-8'>
            {% for candidate in candidates %}
                <div class="well" id='{{ candidate.id }}'>
                    <div class='row'>
                        <div class='col-xs-10'>
                            <div class='col-xs-10'>
                                <h3>{{ candidate.first_name }} {{ candidate.last_name }}<br/><small>{{ candidate.email }}</small></h3>
                            </div>
                            <div class='col-xs-10'>
                                <ul class="list-inline">
                                    <li>Phone: {{ candidate.phone_number | title }}</li>
                                    <li>Preferred Communication: {{ candidate.preferred_communication_method | title }}</li>
                                    <li>Best Time To Contact: {{ candidate.best_contact_time | title }}</li>
                                </ul>
                            </div>
                            <div class='col-xs-10'>
                                <ul class="list-inline">
                                    <li>Contacted On: {{ candidate.initial_contact_date | date:"m/d/Y"}}</li>
                                    <li>Response Form Sent On: {{ candidate.response_form_sent_date | date:"m/d/Y"}}</li>
                                    <li>Response Form Completed On: {{ candidate.response_form_completed_date | date:"m/d/Y"}}</li>
                                </ul>
                            </div>
                            <div class='col-xs-2 text-center'>
                                <a href="{% url 'job_details' candidate.id %}" class="btn btn-primary" role="button">Details</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

{% block scripts %}


{% endblock %}

candidates/templates/candidates/dashboard.html
{% extends "base.html" %}
<div class='row'>
	<div class='col-xs-12 col-sm-6'>
		<h2>Overview</h2>
		<ul class="list-group">
			<li class="list-group-item">
				<a href='#'><span class="badge">18</span>
					Interviews Pending Confirmation
				</a>
			</li>
			<li class="list-group-item">
				<a href='#'><span class="badge">15</span>
					Interviews Awaiting Follow Up
				</a>
			</li>			
			<li class="list-group-item">
				<a href='#'><span class="badge">14</span>
					New Jobs
				</a>
			</li>
			<li class="list-group-item">
				<a href='#'><span class="badge">20</span>
					...
				</a>
			</li>
		</ul>
	</div>
	<div class='col-xs-12 col-sm-6'>
		<h2>Actions</h2>
		<ul class="list-group">
			<li class="list-group-item">
				<a href='#'>
					Update Preferences
				</a>
			</li>
			<li class="list-group-item">
				<a href='#'>
					Update Resume
				</a>
			</li>			
			<li class="list-group-item">
				<a href='#'>
					Update Availability
				</a>
			</li>
			<li class="list-group-item">
				<a href='#'>
					...
				</a>
			</li>
		</ul>		
	</div>
</div>